# Generated by Django 5.0.7 on 2024-08-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_scholarship_foundation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='academic_year_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='eligibility_restrictions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='financial_aid_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='grade_criteria_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='income_criteria_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='major_field_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='managing_organization_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='number_of_recipients_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='product_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='product_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='recommendation_required',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='recruitment_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='recruitment_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='required_documents_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='residency_requirement_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='selection_method_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='specific_qualification_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='support_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='university_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='website_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='foundation_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
