# Generated by Django 5.0.7 on 2024-08-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='foundation_name',
            field=models.CharField(default='재단명없음', max_length=30),
            preserve_default=False,
        ),
    ]
