# Generated by Django 5.0.7 on 2024-08-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birth_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='Unnamed', max_length=10),
        ),
    ]
