version: '3'
services:
  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: gunicorn scholli.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/src/static/
    expose:
      - 80
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/src/static/
volumes:
  static_volume:
  

