version: "3.8"
services:

  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn scholli.wsgi:application --bind 0.0.0.0:8000 -t 120
    environment:
      DJANGO_SETTINGS_MODULE: scholli.settings
      DJANGO_ENV: production
    env_file:
      - .env
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8000
    entrypoint:
      - sh
      - config/docker/entrypoint.prod.sh

  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: ./
    command: celery -A scholli worker -l info
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    environment:
      DJANGO_SETTINGS_MODULE: scholli.settings
      DJANGO_ENV: production
    env_file:
      - .env
    depends_on:
      - web
      - redis
volumes:
  static:
  media: