version: '3'
services:
  api:
    container_name: 'api'
    image: '${API_IMAGE}'
    command: gunicorn scholli.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/src/static/
    expose:
      - 8000
    networks:
      - webnet
  nginx:
      container_name: 'nginx'
      image: '${NGINX_IMAGE}'
      ports:
        - 80:80
      volumes:
        - static_volume:/src/static/
      depends_on:
        - api
      networks:
        - webnet
volumes:
  static_volume:

networks:
  webnet: