version: '3'
services:
  api:
    container_name: 'django-api'
    build:
      context: ./src
      dockerfile: Dockerfile
      cache_from:
        - '${API_IMAGE}'
    image: '${API_IMAGE}'
    command: gunicorn scholli.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    networks:
      - webnet
  nginx:
    build:
     context: ./nginx
     dockerfile: Dockerfile
     cache_from:
          - '${NGINX_IMAGE}'
    image: '${NGINX_IMAGE}'
    depends_on: 
      - api
    ports:
      - 80:80
    networks:
      - webnet
networks:
  webnet: