# Generated by Django 5.0.7 on 2024-08-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='year',
            field=models.SmallIntegerField(default='0'),
        ),
    ]
