# Generated by Django 5.0.7 on 2024-08-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='benefit_tip',
            new_name='advice',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='interview_tip',
            new_name='interviewTip',
        ),
    ]
