# Generated by Django 5.0.7 on 2024-09-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_incomebracket_review_majorcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='incomeBracket',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
