# Generated by Django 5.0.7 on 2024-09-19 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_incomebracket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='incomeBracket',
            new_name='income',
        ),
    ]
